<?php

/**
 * @file
 * Vue views module help and theme functions.
 */

// \Drupal::moduleHandler()->loadInclude('estado_tiempo', 'inc', 'estado_tiempo.theme');

/**
 * Implements hook_theme().
 */
function estado_tiempo_theme($existing, $type, $theme, $path) {
  return [
    'estado_tiempo_icono' => [
      'file' => 'estado_tiempo.theme.inc',
      'template' => 'estado-tiempo-icono',
      'variables' => [
        'fecha' => NULL
      ],
    ],
  ];
}
