<?php

/**
 * @file
 * Vue views module help and theme functions.
 */

// \Drupal::moduleHandler()->loadInclude('estado_tiempo', 'inc', 'estado_tiempo.theme');

/**
 * Implements hook_theme().
 */
function estado_tiempo_theme($existing, $type, $theme, $path) {
  return [
    'estado_tiempo_icono' => [
      //'file' => 'estado_tiempo.theme.inc',
      'template' => 'estado-tiempo-icono',
      'variables' => [
        'fecha' => NULL
      ],
    ],
  ];
}

function template_preprocess_estado_tiempo_icono(&$variables) {
  $fecha = isset($variables['fecha'])? $variables['fecha'] : '';

  $tz = 'Europe/Madrid';
  $timestamp = time();
  $dt = new DateTime("now", new DateTimeZone($tz)); //first argument "must" be a string
  $dt->setTimestamp($timestamp); //adjust the object to correct timestamp
  $variables['fecha'] = $fecha = $dt->format('Y-m-d');
  $variables['hora'] = $hora = $dt->format('H');

  $estadoClimaInfObj  = \Drupal::service('estado_tiempo.EstadoClimaInfo');
  $icono = $estadoClimaInfObj->getIconoClima($fecha, $hora);
  $variables['icono'] = drupal_render($icono);
  $variables['titulo'] = 'Tiempo en Madrid';

}
